### ISSUE TITLE
HTML class='provenance-logo' not read correctly

### ISSUE THREAD

**Issue by danieleongari** [lsmo-epfl/discover-pyrene-mofs#1]
https://github.com/lsmo-epfl/discover-pyrene-mofs/blob/fbc8b3a0ee5ea655f376ebe6025a7a5ed812b497/detail_pyrenemofs/utils.py#L72-L81

it is not correctly reading the class specified in `static/style.css`, resulting in:
![image](https://user-images.githubusercontent.com/25899092/93850999-99523780-fcaf-11ea-86de-c57966711193.png)

@ltalirz you fixed already this problem for `discover-curated-cofs` and I'm puzzled about why here it doesn't work even if the code is identical.

**Comment by ltalirz** [comment]
fixed in 49c05e69010b3da1bdbe270870aded28de173f69
